"""使用者介面模組"""

from .session import NotebookLMSession
from .menus import (
    MENU_MAIN,
    MENU_AUDIO,
    MENU_VIDEO,
    MENU_SLIDE,
    MENU_INFOGRAPHIC,
    MENU_QUIZ,
    MENU_FLASHCARD,
    MENU_REPORT,
    MENU_DOWNLOAD,
)
from .maps import (
    AUDIO_FORMAT_MAP,
    AUDIO_LENGTH_MAP,
    AUDIO_LANG_MAP,
    VIDEO_FORMAT_MAP,
    VIDEO_STYLE_MAP,
    SLIDE_FORMAT_MAP,
    SLIDE_DL_MAP,
    INFOGRAPHIC_ORIENT_MAP,
    INFOGRAPHIC_DETAIL_MAP,
    QUIZ_QTY_MAP,
    QUIZ_DIFF_MAP,
    QUIZ_FMT_MAP,
    REPORT_TYPE_MAP,
)

__all__ = [
    'NotebookLMSession',
    'MENU_MAIN',
    'MENU_AUDIO',
    'MENU_VIDEO',
    'MENU_SLIDE',
    'MENU_INFOGRAPHIC',
    'MENU_QUIZ',
    'MENU_FLASHCARD',
    'MENU_REPORT',
    'MENU_DOWNLOAD',
    'AUDIO_FORMAT_MAP',
    'AUDIO_LENGTH_MAP',
    'AUDIO_LANG_MAP',
    'VIDEO_FORMAT_MAP',
    'VIDEO_STYLE_MAP',
    'SLIDE_FORMAT_MAP',
    'SLIDE_DL_MAP',
    'INFOGRAPHIC_ORIENT_MAP',
    'INFOGRAPHIC_DETAIL_MAP',
    'QUIZ_QTY_MAP',
    'QUIZ_DIFF_MAP',
    'QUIZ_FMT_MAP',
    'REPORT_TYPE_MAP',
]
